title: "cam137"
description: "Pink Floyd & Sciences dures"
url: "https://cam137.org"
baseurl: ""

markdown: kramdown
highlighter: rouge

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: false

plugins:
  - jekyll-feed
  - jekyll-sitemap
