title: "Accueil"
description: "Pink Floyd & Sciences dures"
url: "https://cam137.org"
baseurl: ""

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-last-modified-at
